### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by 63502** [scottkillen-minecraft-mods/Herdcraft#3]
My game occasionally  just randomly crashes when I am attacking Zombies or Skeletons.

This is a crash from a skeleton group, where 1 was on the same level as me, and the other two were in a hole right nearby.

[Crash Log](https://gist.github.com/63502/f11482041fca1c84a846e133e6cc45b0)

**Comment by ScottKillen** [comment]
Unfortunately, this is a clash between this mod and other mods that modify the skeleton. such as Twilight Forest.

**Comment by 63502** [comment]
Is there a way to tell what mod/mods those might be from the crash log? I have 126+ mods installed, and any chance that I won't have to go through and test them all manually is greatly welcome.

**Comment by ScottKillen** [comment]
There is no easy way. When this happens to me, I normally just drop herdcraft
